name: glizer
main: com.beecub.glizer.glizer
version: 1.1.20
author: beecub
website: 'http://glizer.net/'
description: >
             Minecraft Globalizer
commands:
  ban:
    description: Ban player
    usage: |
           /<command> [playername] [message]
  globalban:
    description: Global ban
    usage: |
           /<command> [playername] [message]
  localban:
    description: Local ban
    usage: |
           /<command> [playername] [message]
  tempban:
    description: Temporary Ban
    usage: |
           /<command> [playername] [time] [minutes|hours|days] [message]
  unban:
    description: Unban player
    usage: |
           /<command> [playername] [message]
  note:
    description: Admin comment to player
    usage: |
           /<command> [playername] [value] [message]
  notes:
    description: Show admin comments to player
    usage: |
           /<command> [playername]
  warn:
    description: Caution a player
    usage: |
           /<command> [playername] [value] [comment]
  warnings:
    description: Show cautions to a player
    usage: |
           /<command> [playername]
  register:
    description: Register player to system
    usage: |
           /<command> [password]
  comment:
    description: Add comment to player
    usage: |
           /<command> [playername] [comment]
  comments:
    description: Show comments to player
    usage: |
           /<command> [playername]
  rateplayer:
    description: Rate player
    usage: |
           /<command> [playername] [value]
  rateserver:
    description: Rate server
    usage: |
           /<command> [value]
  profile:
    description: Show players profile
    usage: |
           /<command> [playername]
  editprofile:
    description: Edit profile field
    usage: |
           /<command> [fieldplayername] [text|value]
  clearprofile:
    description: Clear whole profile
    usage: |
           /<command>
  gm:
    description: Send message to a player, whereever on which server he is connectet
    usage: |
           /<command> [playername] [text]
  friends:
    description: Show all friends
    usage: |
           /<command>
  friendsonline:
    description: Show all online friends and on which server theyre online
    usage: |
           /<command>
  addfriend:
    description: Add a player to your friend list
    usage: |
           /<command> [playername]
  removefriend:
    description: Remove a friend from your friend list
    usage: |
           /<command> [playername]
  glizerhelp:
    description: Help to glizer plugin
    usage: |
           /<command> [page]
  glizerreload:
    description: Reload glizer configuration file
    usage: |
           /<command> [reload]
  addwhitelist:
    description: Add player to whitelist
    usage: |
           /<command> [playername]
  removewhitelist:
    description: Remove player from whitelist
    usage: |
           /<command> [playername]
  theanswertolifetheuniverseandeverything:
    description: The Answer to Life the Universum and Everything.
    usage: |
           /<command>